-- CREATE TABLE burgers(
--   id INT NOT NULL AUTO_INCREMENT,
--   title VARCHAR(80),
--   ingredients VARCHAR(300),
--   price INT NOT NULL,
--   PRIMARY KEY(id)
-- )

-- INSERT INTO burgers(
--   title,
--   ingredients,
--   price
-- )
-- Values(
--   "Hamburger",
--   "Buns, Patty, Ketchup, Pickles, Lettuce",
--   5
-- )